// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpiredSettledRunsOfTenant = `-- name: CountExpiredSettledRunsOfTenant :one
SELECT count(*) AS runs, COALESCE(sum(e.task_instances), 0)::bigint AS task_instances
FROM (
  SELECT (SELECT count(*) FROM task_instances ti WHERE ti.dag_run_id = r.id) AS task_instances
  FROM dag_runs r
  WHERE r.tenant_id = $1
    AND r.state IN ('success', 'failed')
    AND r.ended_at < $2
    AND NOT EXISTS (
      SELECT 1 FROM task_instances ti
      WHERE ti.dag_run_id = r.id
        AND ti.state NOT IN ('success', 'failed', 'skipped', 'upstream_failed'))
    AND NOT EXISTS (
      SELECT 1 FROM staging_volumes s
      WHERE s.tenant_id = r.tenant_id AND s.run_id = r.id::text AND s.state = 'active')
  LIMIT $3
) e
`

type CountExpiredSettledRunsOfTenantParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	MaxRuns  int32              `json:"max_runs"`
}

type CountExpiredSettledRunsOfTenantRow struct {
	Runs          int64 `json:"runs"`
	TaskInstances int64 `json:"task_instances"`
}

// The dry-run count for one tenant: the same predicate as
// LockExpiredSettledRuns, with no lock, through the same partial index, and
// stopped after max_runs runs so its cost stays bounded however long the
// history is. The janitor reports a total that reached the cap as a lower bound.
func (q *Queries) CountExpiredSettledRunsOfTenant(ctx context.Context, arg CountExpiredSettledRunsOfTenantParams) (CountExpiredSettledRunsOfTenantRow, error) {
	row := q.db.QueryRow(ctx, countExpiredSettledRunsOfTenant, arg.TenantID, arg.Cutoff, arg.MaxRuns)
	var i CountExpiredSettledRunsOfTenantRow
	err := row.Scan(&i.Runs, &i.TaskInstances)
	return i, err
}

const countExpiredSystemAuditLog = `-- name: CountExpiredSystemAuditLog :one
SELECT count(*) FROM (
  SELECT 1 FROM audit_log a
  WHERE a.tenant_id IS NULL AND a.occurred_at < $1
  LIMIT $2
) e
`

type CountExpiredSystemAuditLogParams struct {
	Cutoff  pgtype.Timestamptz `json:"cutoff"`
	MaxRows int32              `json:"max_rows"`
}

// System audit rows (no tenant) older than the cutoff, at most max_rows.
func (q *Queries) CountExpiredSystemAuditLog(ctx context.Context, arg CountExpiredSystemAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiredSystemAuditLog, arg.Cutoff, arg.MaxRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiredTenantAuditLog = `-- name: CountExpiredTenantAuditLog :one
SELECT count(*) FROM (
  SELECT 1 FROM audit_log a
  WHERE a.tenant_id = $1 AND a.occurred_at < $2
  LIMIT $3
) e
`

type CountExpiredTenantAuditLogParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	MaxRows  int32              `json:"max_rows"`
}

// Audit rows of one tenant older than the cutoff, at most max_rows.
func (q *Queries) CountExpiredTenantAuditLog(ctx context.Context, arg CountExpiredTenantAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiredTenantAuditLog, arg.TenantID, arg.Cutoff, arg.MaxRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDagRunsByID = `-- name: DeleteDagRunsByID :execrows
DELETE FROM dag_runs
WHERE id IN (
  SELECT r.id FROM dag_runs r
  WHERE r.tenant_id = $1 AND r.id = ANY($2::uuid[])
    AND NOT EXISTS (SELECT 1 FROM task_instances ti WHERE ti.dag_run_id = r.id)
    AND NOT EXISTS (SELECT 1 FROM xcom_index x WHERE x.dag_run_id = r.id)
  LIMIT $3)
`

type DeleteDagRunsByIDParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
	RowLimit int32         `json:"row_limit"`
}

// Removes the locked runs whose children are all gone, up to row_limit.
func (q *Queries) DeleteDagRunsByID(ctx context.Context, arg DeleteDagRunsByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDagRunsByID, arg.TenantID, arg.RunIds, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSystemAuditLog = `-- name: DeleteSystemAuditLog :execrows
DELETE FROM audit_log
WHERE id IN (
  SELECT a.id FROM audit_log a
  WHERE a.tenant_id IS NULL AND a.occurred_at < $1
  ORDER BY a.occurred_at
  LIMIT $2)
`

type DeleteSystemAuditLogParams struct {
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	RowLimit int32              `json:"row_limit"`
}

func (q *Queries) DeleteSystemAuditLog(ctx context.Context, arg DeleteSystemAuditLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSystemAuditLog, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskInstanceHistoryOfRuns = `-- name: DeleteTaskInstanceHistoryOfRuns :execrows
DELETE FROM task_instance_history
WHERE history_id IN (
  SELECT h.history_id FROM task_instance_history h
  JOIN task_instances ti ON ti.id = h.task_instance_id
  WHERE ti.tenant_id = $1 AND ti.dag_run_id = ANY($2::uuid[])
  LIMIT $3)
`

type DeleteTaskInstanceHistoryOfRunsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
	RowLimit int32         `json:"row_limit"`
}

func (q *Queries) DeleteTaskInstanceHistoryOfRuns(ctx context.Context, arg DeleteTaskInstanceHistoryOfRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskInstanceHistoryOfRuns, arg.TenantID, arg.RunIds, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskInstancesOfRuns = `-- name: DeleteTaskInstancesOfRuns :execrows
DELETE FROM task_instances
WHERE id IN (
  SELECT ti.id FROM task_instances ti
  WHERE ti.tenant_id = $1 AND ti.dag_run_id = ANY($2::uuid[])
  LIMIT $3)
`

type DeleteTaskInstancesOfRunsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
	RowLimit int32         `json:"row_limit"`
}

func (q *Queries) DeleteTaskInstancesOfRuns(ctx context.Context, arg DeleteTaskInstancesOfRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskInstancesOfRuns, arg.TenantID, arg.RunIds, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskStateHistoryOfRuns = `-- name: DeleteTaskStateHistoryOfRuns :execrows
DELETE FROM task_state_history
WHERE id IN (
  SELECT h.id FROM task_state_history h
  JOIN task_instances ti ON ti.id = h.task_instance_id
  WHERE ti.tenant_id = $1 AND ti.dag_run_id = ANY($2::uuid[])
  LIMIT $3)
`

type DeleteTaskStateHistoryOfRunsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
	RowLimit int32         `json:"row_limit"`
}

func (q *Queries) DeleteTaskStateHistoryOfRuns(ctx context.Context, arg DeleteTaskStateHistoryOfRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskStateHistoryOfRuns, arg.TenantID, arg.RunIds, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTenantAuditLog = `-- name: DeleteTenantAuditLog :execrows
DELETE FROM audit_log
WHERE id IN (
  SELECT a.id FROM audit_log a
  WHERE a.tenant_id = $1 AND a.occurred_at < $2
  ORDER BY a.occurred_at
  LIMIT $3)
`

type DeleteTenantAuditLogParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	RowLimit int32              `json:"row_limit"`
}

func (q *Queries) DeleteTenantAuditLog(ctx context.Context, arg DeleteTenantAuditLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenantAuditLog, arg.TenantID, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteXComIndexOfRuns = `-- name: DeleteXComIndexOfRuns :execrows
DELETE FROM xcom_index
WHERE id IN (
  SELECT x.id FROM xcom_index x
  WHERE x.tenant_id = $1 AND x.dag_run_id = ANY($2::uuid[])
  LIMIT $3)
`

type DeleteXComIndexOfRunsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
	RowLimit int32         `json:"row_limit"`
}

func (q *Queries) DeleteXComIndexOfRuns(ctx context.Context, arg DeleteXComIndexOfRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteXComIndexOfRuns, arg.TenantID, arg.RunIds, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTenantIDs = `-- name: ListTenantIDs :many

SELECT id FROM tenants ORDER BY id
`

// Retention janitor (performance item D5). Every statement is tenant scoped and
// bounded; the janitor in internal/retention paces and caps them.
func (q *Queries) ListTenantIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredSettledRuns = `-- name: LockExpiredSettledRuns :many
SELECT r.id
FROM dag_runs r
WHERE r.tenant_id = $1
  AND r.state IN ('success', 'failed')
  AND r.ended_at < $2
  AND NOT EXISTS (
    SELECT 1 FROM task_instances ti
    WHERE ti.dag_run_id = r.id
      AND ti.state NOT IN ('success', 'failed', 'skipped', 'upstream_failed'))
  AND NOT EXISTS (
    SELECT 1 FROM staging_volumes s
    WHERE s.tenant_id = r.tenant_id AND s.run_id = r.id::text AND s.state = 'active')
ORDER BY r.ended_at
LIMIT $3
FOR UPDATE OF r SKIP LOCKED
`

type LockExpiredSettledRunsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	MaxRuns  int32              `json:"max_runs"`
}

// A tenant's runs that settled (success or failed) before the cutoff, oldest
// first, whose task instances are all settled and that no live staging volume
// still points at. "Settled" is the predicate the pod reconciler's settled-run
// collection uses too: run in success or failed, and no task instance outside
// success, failed, skipped and upstream_failed. none is unsettled on purpose:
// it is a task a clear just reset, waiting to be scheduled, while the run row
// still says success until the clear reopens it. Any state added later counts
// as unsettled, so it is kept rather than deleted. The janitor calls this once
// per batch, so a run whose children span several batches is re-checked each
// time. FOR UPDATE keeps the run row itself from changing, and SKIP LOCKED
// lets the janitor pass over a run another transaction holds. It does NOT stop
// a clear: a clear resets task_instances before it touches the run row, so the
// janitor then locks and re-checks the task instances
// (LockTaskInstancesOfRuns) before it deletes anything.
func (q *Queries) LockExpiredSettledRuns(ctx context.Context, arg LockExpiredSettledRunsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockExpiredSettledRuns, arg.TenantID, arg.Cutoff, arg.MaxRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskInstancesOfRuns = `-- name: LockTaskInstancesOfRuns :many
SELECT ti.dag_run_id,
       (ti.state IN ('success', 'failed', 'skipped', 'upstream_failed'))::boolean AS settled
FROM task_instances ti
WHERE ti.tenant_id = $1 AND ti.dag_run_id = ANY($2::uuid[])
FOR UPDATE OF ti NOWAIT
`

type LockTaskInstancesOfRunsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	RunIds   []pgtype.UUID `json:"run_ids"`
}

type LockTaskInstancesOfRunsRow struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	Settled  bool        `json:"settled"`
}

// Locks every task instance of the locked runs and reports whether each is
// still settled. A clear resets task instances without locking the run row
// first, so the run lock alone does not keep it out: a clear that committed
// since LockExpiredSettledRuns shows here as an unsettled state, and the
// janitor drops that run from the batch. Once these locks are held no clear can
// change the rows until the batch commits. NOWAIT: a task instance another
// transaction is writing (a clear in flight) fails the lock with
// lock_not_available instead of waiting, because that clear will next update
// the run row the janitor holds, and waiting would deadlock; the janitor skips
// the batch and retries on a later cycle.
func (q *Queries) LockTaskInstancesOfRuns(ctx context.Context, arg LockTaskInstancesOfRunsParams) ([]LockTaskInstancesOfRunsRow, error) {
	rows, err := q.db.Query(ctx, lockTaskInstancesOfRuns, arg.TenantID, arg.RunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockTaskInstancesOfRunsRow{}
	for rows.Next() {
		var i LockTaskInstancesOfRunsRow
		if err := rows.Scan(&i.DagRunID, &i.Settled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRetentionPurge = `-- name: RecordRetentionPurge :exec
INSERT INTO audit_log (tenant_id, action, resource_type, metadata)
VALUES ($1, 'retention.purge', 'audit_log',
        jsonb_build_object('table', 'audit_log', 'rows', $2::bigint, 'cutoff', $3::timestamptz))
`

type RecordRetentionPurgeParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Rows     int64              `json:"rows"`
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
}

// One audit entry per scope a retention cycle purged audit rows from, so the
// purge itself is on the record. tenant_id NULL is the system rows.
func (q *Queries) RecordRetentionPurge(ctx context.Context, arg RecordRetentionPurgeParams) error {
	_, err := q.db.Exec(ctx, recordRetentionPurge, arg.TenantID, arg.Rows, arg.Cutoff)
	return err
}
