// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyDefaultRolePermissions = `-- name: CopyDefaultRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT nr.id, rp.permission_id
FROM roles dr
JOIN tenants d ON d.id = dr.tenant_id AND d.name = 'default'
JOIN role_permissions rp ON rp.role_id = dr.id
JOIN roles nr ON nr.tenant_id = $1::uuid AND nr.name = dr.name
WHERE dr.is_system
ON CONFLICT DO NOTHING
`

// Grant each copied built-in role the same permissions as its "default" twin.
func (q *Queries) CopyDefaultRolePermissions(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, copyDefaultRolePermissions, tenantID)
	return err
}

const copyDefaultSystemRoles = `-- name: CopyDefaultSystemRoles :exec
INSERT INTO roles (tenant_id, name, description, is_system)
SELECT $1::uuid, r.name, r.description, true
FROM roles r
JOIN tenants d ON d.id = r.tenant_id AND d.name = 'default'
WHERE r.is_system
ON CONFLICT (tenant_id, name) DO NOTHING
`

// Give a tenant the built-in roles the migrations seed for "default". Copying
// keeps every tenant's ladder equal to default's as later migrations change it.
func (q *Queries) CopyDefaultSystemRoles(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, copyDefaultSystemRoles, tenantID)
	return err
}

const insertDefaultPool = `-- name: InsertDefaultPool :exec
INSERT INTO pools (tenant_id, name, slots, description, is_default)
SELECT $1::uuid, p.name, p.slots, p.description, true
FROM pools p
JOIN tenants d ON d.id = p.tenant_id AND d.name = 'default'
WHERE p.is_default
ON CONFLICT (tenant_id, name) DO UPDATE SET is_default = true, updated_at = now()
  WHERE NOT pools.is_default
`

// The implicit default pool every tenant needs (migration 023 seeds it for
// "default"), copied from default's so the slot count stays in step.
func (q *Queries) InsertDefaultPool(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertDefaultPool, tenantID)
	return err
}

const insertTenantIfMissing = `-- name: InsertTenantIfMissing :execrows
INSERT INTO tenants (name, display_name)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
`

type InsertTenantIfMissingParams struct {
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name"`
}

// Service API (#1283): create a tenant by name, or do nothing when it exists.
// Zero rows affected means it already existed.
func (q *Queries) InsertTenantIfMissing(ctx context.Context, arg InsertTenantIfMissingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTenantIfMissing, arg.Name, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTenantRolePermissions = `-- name: ListTenantRolePermissions :many
SELECT (r.name || ':' || p.action || ':' || p.resource)::text AS grant_key
FROM roles r
JOIN tenants t ON t.id = r.tenant_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE t.name = $1 AND r.is_system
`

// "role:action:resource" for every grant of a tenant's built-in roles.
func (q *Queries) ListTenantRolePermissions(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTenantRolePermissions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_key string
		if err := rows.Scan(&grant_key); err != nil {
			return nil, err
		}
		items = append(items, grant_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantHasDefaultPool = `-- name: TenantHasDefaultPool :one
SELECT EXISTS (
    SELECT 1 FROM pools p JOIN tenants t ON t.id = p.tenant_id
    WHERE t.name = $1 AND p.is_default
)::bool AS has_default
`

func (q *Queries) TenantHasDefaultPool(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantHasDefaultPool, name)
	var has_default bool
	err := row.Scan(&has_default)
	return has_default, err
}

const upsertDefaultPoolSlots = `-- name: UpsertDefaultPoolSlots :exec
INSERT INTO pools (tenant_id, name, slots, description, is_default)
VALUES ($1::uuid, $2, $3, 'Default pool', true)
ON CONFLICT (tenant_id, name) DO UPDATE SET slots = EXCLUDED.slots, is_default = true, updated_at = now()
`

type UpsertDefaultPoolSlotsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Slots    int32       `json:"slots"`
}

// Sizes a tenant's default pool to an explicit slot count: inserts it under the
// given name with the seed description, or re-sizes the row already there. A
// row with that name left without is_default (a tenant created before the
// default pool was seeded per tenant) is marked default, so the delete guard
// and the pools view treat it as the pool the scheduler falls back to.
func (q *Queries) UpsertDefaultPoolSlots(ctx context.Context, arg UpsertDefaultPoolSlotsParams) error {
	_, err := q.db.Exec(ctx, upsertDefaultPoolSlots, arg.TenantID, arg.Name, arg.Slots)
	return err
}
