// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: xcom.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredXComIndex = `-- name: DeleteExpiredXComIndex :exec
DELETE FROM xcom_index WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredXComIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredXComIndex)
	return err
}

const deleteXComIndexForTasks = `-- name: DeleteXComIndexForTasks :many
DELETE FROM xcom_index
WHERE dag_run_id = $1 AND task_id = ANY($2::text[])
RETURNING redis_key
`

type DeleteXComIndexForTasksParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskIds  []string    `json:"task_ids"`
}

// Removes the XCom index rows of task instances a clear is resetting (#1131) and
// returns their backend keys, so the stored values can be deleted too. XCom
// carries no try number, so rows left behind would serve the cleared attempt's
// values to the next attempt's downstream.
func (q *Queries) DeleteXComIndexForTasks(ctx context.Context, arg DeleteXComIndexForTasksParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteXComIndexForTasks, arg.DagRunID, arg.TaskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var redis_key string
		if err := rows.Scan(&redis_key); err != nil {
			return nil, err
		}
		items = append(items, redis_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getXComByNames = `-- name: GetXComByNames :one
SELECT x.redis_key, x.content_type, x.size_bytes, x.created_at
FROM xcom_index x
JOIN dag_runs dr ON dr.id = x.dag_run_id
JOIN dags d ON d.id = dr.dag_id
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $1 AND d.dag_id = $2 AND dr.run_id = $3 AND x.task_id = $4 AND x.key = $5
  AND x.expires_at > now()
`

type GetXComByNamesParams struct {
	Name   string `json:"name"`
	DagID  string `json:"dag_id"`
	RunID  string `json:"run_id"`
	TaskID string `json:"task_id"`
	Key    string `json:"key"`
}

type GetXComByNamesRow struct {
	RedisKey    string             `json:"redis_key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int32              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetXComByNames(ctx context.Context, arg GetXComByNamesParams) (GetXComByNamesRow, error) {
	row := q.db.QueryRow(ctx, getXComByNames,
		arg.Name,
		arg.DagID,
		arg.RunID,
		arg.TaskID,
		arg.Key,
	)
	var i GetXComByNamesRow
	err := row.Scan(
		&i.RedisKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getXComEntry = `-- name: GetXComEntry :one
SELECT redis_key, content_type, size_bytes, created_at
FROM xcom_index
WHERE dag_run_id = $1 AND task_id = $2 AND key = $3 AND expires_at > now()
`

type GetXComEntryParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Key      string      `json:"key"`
}

type GetXComEntryRow struct {
	RedisKey    string             `json:"redis_key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int32              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetXComEntry(ctx context.Context, arg GetXComEntryParams) (GetXComEntryRow, error) {
	row := q.db.QueryRow(ctx, getXComEntry, arg.DagRunID, arg.TaskID, arg.Key)
	var i GetXComEntryRow
	err := row.Scan(
		&i.RedisKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listXComEntries = `-- name: ListXComEntries :many
SELECT x.key AS key, x.created_at AS created_at
FROM xcom_index x
JOIN dag_runs dr ON dr.id = x.dag_run_id
JOIN dags d ON d.id = dr.dag_id
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $1 AND d.dag_id = $2 AND dr.run_id = $3 AND x.task_id = $4
  AND x.expires_at > now()
ORDER BY x.key
`

type ListXComEntriesParams struct {
	Name   string `json:"name"`
	DagID  string `json:"dag_id"`
	RunID  string `json:"run_id"`
	TaskID string `json:"task_id"`
}

type ListXComEntriesRow struct {
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListXComEntries(ctx context.Context, arg ListXComEntriesParams) ([]ListXComEntriesRow, error) {
	rows, err := q.db.Query(ctx, listXComEntries,
		arg.Name,
		arg.DagID,
		arg.RunID,
		arg.TaskID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListXComEntriesRow{}
	for rows.Next() {
		var i ListXComEntriesRow
		if err := rows.Scan(&i.Key, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordXCom = `-- name: RecordXCom :exec
INSERT INTO xcom_index (tenant_id, dag_run_id, task_id, key, redis_key, size_bytes, content_type, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (dag_run_id, task_id, key) DO UPDATE SET
    redis_key = EXCLUDED.redis_key,
    size_bytes = EXCLUDED.size_bytes,
    content_type = EXCLUDED.content_type,
    created_at = now(),
    expires_at = EXCLUDED.expires_at
`

type RecordXComParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DagRunID    pgtype.UUID        `json:"dag_run_id"`
	TaskID      string             `json:"task_id"`
	Key         string             `json:"key"`
	RedisKey    string             `json:"redis_key"`
	SizeBytes   int32              `json:"size_bytes"`
	ContentType string             `json:"content_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RecordXCom(ctx context.Context, arg RecordXComParams) error {
	_, err := q.db.Exec(ctx, recordXCom,
		arg.TenantID,
		arg.DagRunID,
		arg.TaskID,
		arg.Key,
		arg.RedisKey,
		arg.SizeBytes,
		arg.ContentType,
		arg.ExpiresAt,
	)
	return err
}
